# Generated by Django 3.1 on 2020-08-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('EmailID', models.EmailField(max_length=122, null=True)),
                ('gender', models.CharField(max_length=122, null=True)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('Permanent_Address', models.CharField(max_length=225, null=True)),
                ('PinCode', models.CharField(max_length=10, null=True)),
                ('Mob_No', models.CharField(max_length=10, null=True)),
                ('Parents_Mob_No', models.CharField(max_length=10, null=True)),
                ('HSSC_Stream', models.CharField(max_length=122, null=True)),
                ('Total_Marks', models.CharField(max_length=122, null=True)),
                ('Marks_Obtained', models.CharField(max_length=122, null=True)),
                ('file', models.FileField(upload_to='')),
                ('file1', models.FileField(null=True, upload_to='')),
                ('file2', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
