# Generated by Django 3.1 on 2020-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admission_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone1',
        ),
    ]
