# Generated by Django 3.1 on 2020-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200826_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date1',
        ),
    ]
