# Generated by Django 3.1 on 2020-09-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200904_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestNews',
            new_name='LatestNews_TopImage',
        ),
    ]
