# Generated by Django 3.1 on 2020-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_latestnews_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews_box1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullets', models.CharField(max_length=100)),
            ],
        ),
    ]
