# Generated by Django 3.1 on 2020-09-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_latestnews_box1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews_box2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=100)),
            ],
        ),
    ]
