# Generated by Django 3.1 on 2020-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_latestnews_box2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(upload_to='pic/')),
                ('Pic_title', models.CharField(max_length=100)),
                ('pic_desc', models.TextField()),
            ],
        ),
    ]
