# Generated by Django 3.1 on 2020-09-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_index_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_Profile',
            new_name='Index_Profile1',
        ),
    ]
