# Generated by Django 3.1 on 2020-09-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200905_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_Profile1',
            new_name='Index_Profile',
        ),
    ]
