# Generated by Django 3.1 on 2020-09-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200905_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_Profile',
            new_name='Index_Profile1',
        ),
    ]
