# Generated by Django 3.1 on 2020-09-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200905_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Profile2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic2', models.ImageField(upload_to='pic/')),
                ('Pic_title2', models.CharField(max_length=100)),
                ('pic_desc2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Index_Profile3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic3', models.ImageField(upload_to='pic/')),
                ('Pic_title3', models.CharField(max_length=100)),
                ('pic_desc3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Index_Profile4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic4', models.ImageField(upload_to='pic/')),
                ('Pic_title4', models.CharField(max_length=100)),
                ('pic_desc4', models.TextField()),
            ],
        ),
    ]
