# Generated by Django 3.1 on 2020-09-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_index_profile2_index_profile3_index_profile4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index_Profile2',
        ),
        migrations.DeleteModel(
            name='Index_Profile3',
        ),
        migrations.DeleteModel(
            name='Index_Profile4',
        ),
    ]
